asab/application.py, asab/config.py
You can provide working_dir configuration directive to override this.
Fixes #12
=> A working dir during daemonise is not changed by default.

asab/config.py, asab/log.py
Adding a logging to file possibility along with basic config settings.
=> Adding loggin to file possibility with basic settings.

asab/application.py
I want to be able to set path to a log file via command line argument like this:
```
./asab-app.py -l /var/log/asab-app.log
```
=> Add a command line argument for setting a log file path.

asab/storage/__init__.py, asab/storage/inmemory.py, asab/storage/mongodb.py, asab/storage/service.py, asab/storage/upsertor.py, doc/TODO.md, examples/storage.py
Upsertor :-)
Storage backends: in-memory and MongoDB
=> Add an ASAB Storage module.

asab/application.py, doc/TODO.md, examples/argparser.py
As a developer I want to be able to add command line arguments to the application.
=> Allow custom argparser.

asab/mom/__init__.py, asab/mom/abc.py, asab/mom/amqp/__init__.py, asab/mom/amqp/subscription.py, asab/mom/broker.py, asab/mom/service.py, doc/asab/mom/index.rst, doc/index.rst, examples/mom.py
That's a similar concept to e.g. Celery.
=> Add an Message Oriented Architecture (aka tasks)

asab/proactor/__init__.py, asab/proactor/service.py, doc/TODO.md
https://en.wikipedia.org/wiki/Proactor_pattern
=> Add a proactor service

asab/metrics/metrics.py, asab/metrics/service.py
See https://en.wikipedia.org/wiki/Duty_cycle for better understanding of this metrics.
=> Add a duty-cycle metrics.

doc/asab/config.rst
=> Fixing docs typo

asab/config.py
http://jira.teskalabs.int:8080/browse/PLUM-554
=> PLUM-554: Do not allow None values in Config object

asab/config.py
please merge include environment variable fix
=> Plum 582 mode config includes

doc/asab/mom/index.rst, doc/get-started.rst, doc/tutorial/web/chapter1.rst
=> Fix doc typos

asab/web/rest/__init__.py, asab/web/rest/json.py
http://jira.teskalabs.int:8080/browse/PLUM-767
=> PLUM-767: Add JSON schema handler Fixes: #69

asab/web/rest/json.py, examples/data/sample_json_schema.json, examples/json_schema.py
Add sample JSON schema file to data folder. Add JSON schema example file
http://jira.teskalabs.int:8080/browse/PLUM-851
&
http://jira.teskalabs.int:8080/browse/PLUM-848
=> PLUM-851: Allow method json_schema_handler specify JSON schema in a file

asab/config.py
=> Plum 582 nested includes

asab/pdict.py
http://jira.teskalabs.int:8080/browse/PLUM-944
=> PLUM-944: Update asab.pdict to use shelve. Fixes: #83

asab/config.py
=> Introduce a configurable object.

asab/pdict.py, examples/pdict.py
One of my idea :bulb: is to add `load` to `__init__` if file exist
=> Explicit store in pdict

CONTRIBUTING.md
I was told to write something like this on wiki. Wiki is only linking here.
http://jira.teskalabs.int:8080/browse/PLUM-1011
=> PLUM-1011: Add pep8/flake8 to contribution guideline

asab/application.py, examples/application_states.py
This request fixes all problems in #51 . Tested on provided examples.
=> Init time separation

asab/log.py, doc/asab/log.rst
=> Allow to force logging to console.

asab/config.py, asab/log.py
=> Add a file size limit to a file logger.

asab/config.py, asab/log.py, asab/metrics/service.py
=> Fine-grained log levels

doc/tutorial/web/rest/asab.webservice.md
@ateska Please see and comment. Its .md but I think I can convert it to the .rst
=> Feature rest tutorial

asab/application.py, asab/config.py, asab/logman/log.py, asab/metrics/service.py
https://github.com/TeskaLabs/asab/issues/123
=> Use docker name instead of container id in logs and metrics

asab/application.py, asab/task.py, examples/task.py
Task service is for managed execution of fire-and-forget, one-off, background tasks.
The task is a coroutine, future (asyncio.ensure_future) or task (asyncio.create_task).
The task is executed in the main event loop.
The task should be a relatively short-lived (~5 seconds) asynchronous procedure.
The result of the task is collected (and discarted) automatically and if there was an exception, it will be printed to the log.
=> Add a Task Service

asab/metrics/metrics.py, asab/metrics/service.py, examples/metrics.py
=> Introduce EPS counter metric.

asab/application.py, asab/docker/service.py, asab/log.py, asab/zookeeper/__init__.py
=> Add colors into log

asab/config.py, asab/zookeeper/service.py, examples/zookeeper.py
1. I have removed '_from_include_build_url' so all 3 types of URLs are handled in '_include_from_zookeeper'. 
2. Repress zookeeper aborting message.
3. Altered the connection error message.
4. Renaming few  Config defaults in asab/zookeeper/service.py
=> Asab zookeeper feature

asab/storage/elasticsearch.py
botched the name, the changes only concern the storage service.
=> Expand es storage service to use json queries

asab/zookeeper/service.py
=> ZooKeeper service update

asab/web/container.py
This is a rework on how web containers are started in the ASAB.
**It is the central part of the ASAB**, so it is important that you are informed about this change and that we are aware of any issue that could eventually arise in ASAB microservices.
The reason of this change is a strange bug identified in SeaCat PKI during a startup sequence; it seems to be a race condition in the startup sequence. I analysed this down to a unnecessary complex startup of the ASAB web containers.
=> Rework of the ASAB web container startup sequence.

doc/tutorial/web/chapter1.rst
Flag is required for web server start.
=> Add -w flag

asab/application.py, asab/net/tls.py
The current lifecycle implementation is unnecessary complex, this is an attempt to reduce that complexity.
The functionality remains the same.
Please review and test properly, this is a core component.
I tested this on BSPump successfully.
=> Refactorization of the application lifecycle to reduce its implementation complexity.

asab/web/tenant/service.py
Tenants received from URL source are converted to proper Tenant objects.
fixes #144
=> Convert tenants to Tenant objects in _update_tenants

asab/log.py
and if no logging has been configured by command-line / configuration file etc.
Solves #154
=> Asab logging will use stderr (console) when running in Docker

asab/application.py, asab/config.py, asab/log.py, doc/asab/config.rst, doc/asab/log.rst, examples/data/logging-file.conf, examples/logging-file.py
@ateska @Plesoun @mpavelka This commit adds a possibility to specify hostname variable in the logging of files, thus allowing more instances of the same application to log to different files.
=> Add a possibility to specify hostname in ASAB logging.

asab/api/service.py, asab/application.py, asab/config.py, asab/web/container.py, asab/web/service.py
=> Revert "Draft: Web section config refactoring"

asab/api/__init__.py, asab/api/service.py, asab/api/web_handler.py, asab/application.py, asab/config.py, asab/web/container.py, asab/web/service.py, asab/zookeeper/container.py, asab/zookeeper/service.py, examples/webserver.py, examples/zookeeper.conf, examples/zookeeper.py
=> Asab web refactoring

asab/zookeeper/builder.py
Condition for Section-key check is fixed.
Now there is more flexibility in parsing paths.
=> Zookeeper-builder :  better handling of url 

asab/web/authz/service.py, examples/web-authz-userinfo.conf, examples/web-authz-userinfo.py
Fixes #176 
Non-200 userinfo responses are logged and not cached. `None` is returned.
Updated `example/web-authz-userinfo.py`
=> Handle userinfo failure

asab/web/rest/json.py
f-strings removed. 
I find warnings redundant, where the specific exception is raised, containing already all possible information.
=> JSON schema handler exceptions

asab/pubsub.py
I had trouble using unsubscribe() and this helped me a lot...
=> PubSub unsubscribe fix

asab/api/web_handler.py, asab/metrics/prometheus.py
It is rather a draft. 
I used Prometheus target and curl to get the metrics. Thus, Prometheus target must be configured to get this endpoint.
As there can be many metric values, I thought some aggregation might be helpful.
Questions: 
- Should I make new separate target? 
- Should I add more aggregation functions? 
- Is curl ok?
`watch curl localhost:8089/asab/v1/metrics/watch`
```
--------------------------------------------------------------------------------------------------------------------------
Metric name               | Value name                                                        | Value
--------------------------------------------------------------------------------------------------------------------------
web_requests_duration_max | labels(method='GET', …
```
=> Metrics readable from command line

asab/metrics/influxdb.py, asab/metrics/metrics.py, asab/metrics/openmetric.py, asab/metrics/prometheus.py, asab/metrics/service.py, asab/web/accesslog.py, asab/web/service.py, examples/metrics-requests.py, test/test_influxdb.py
Work in progress. 
- Cumulative histogram added.
- Histogram translated into OpenMetric format. 
- Web request duration histogram added.
- I fixed the Influx target, so it can handle web request metrics.
- Test for influxdb_format function added.
- Histogram not yet presented to Influx.
=> Histogram implementation

asab/api/service.py
one more extra piece of information for my remote-control :)
=> containarization advertised

asab-manifest.py, asab/api/log.py, asab/api/service.py, asab/storage/upsertor.py
=> Make datetimes UTC-aware

asab/alert.py, asab/library/providers/filesystem.py, asab/task.py, asab/web/authn/pubkeyauth.py, asab/web/session/cookies.py
=> Flake8 E275

asab/api/service.py
It will help me to test the new remote-control version and hopefully won't destroy anything.
=> Advertisement ID

asab/alert.py
This is the only change that is vital for the current state of the remote-control. 
However, I've gathered some more notes and TODOs here: https://github.com/TeskaLabs/asab/issues/285
=> Updating Alerts

asab/library/providers/azurestorage.py, asab/library/providers/filesystem.py, asab/library/providers/zookeeper.py
Improved logging in -v mode that provides info about where each library provider is connected 
https://github.com/TeskaLabs/asab/issues/254
=> Improved logging

asab/api/doc.py
Fixed swagger not working and made security optional.
=> fixed swagger and made security be optional

asab/metrics/metrics.py, asab/metrics/service.py, test/test_metrics/test_histogram.py
So I can fulfill my hypothesis from the documentation. https://asab.readthedocs.io/en/latest/asab/metrics.html#initial-values
=> Init values in histograms

asab/web/websocket.py
=> Documenting WebSocket endpoint

asab/log.py, asab/metrics/native.py
I added the errors and warnings counter. 
I found the Logger Manager Singleton object as a perfect place for the LogCounter to live in. I just hope that the _StrucutedDataLogger covers all logging in asab. 
I'm not sure where to initialize the Counter - logging is initialized much earlier than MetricsService. I didn't want to make logging dependent on Metrics Service, so I put just a `None` placeholder to the manager and initialized the LogCounter in Native Metrics. 
Adding the logger name as a dynamic tag is quite a nice feature, isn't it? :)
=> LogCounter

asab/task.py
Improvements:
1) New tasks are added to a task service thru queue, which leads to a faster execution of the task (in ideal conditions)
2)  New `run_forever()` method for tasks that you want to let run forever, including restart after a task failure
=> Improving a task service

asab/web/container.py
* Ability to push configuration to SSL Context
* Ability to specify maximum body size
=> Improvements in asab.web

asab/application.py, asab/docker/__init__.py
=> Improved docker detection.

asab/metrics/service.py, test/test_metrics/baseclass.py, test/test_metrics/test_agg_counter.py, test/test_metrics/test_counter.py, test/test_metrics/test_counter_with_dynamic_tags.py, test/test_metrics/test_duty_cycle.py, test/test_metrics/test_eps_counter.py, test/test_metrics/test_gauge.py, test/test_metrics/test_histogram.py, test/test_metrics/test_validation.py
instance ID env variable is tested on Linux; Docker containers are not tested
=> Metrics: Adds INSTANCE_ID and appClass to tags

doc/asab/metrics.rst
Related to https://github.com/TeskaLabs/asab/pull/358.
=> Updates the documentation following the change in the timestamp creation logic

asab/config.py, asab/utils.py
For easier usage outside config parsing.
=> Extract the string-to-boolean conversion into utils

asab/api/discovery.py, asab/api/service.py, examples/service-discovery.py
-  fix since Docker Service was removed and node_id added
=> Fix: Service Discovery

asab/library/item.py, asab/library/providers/abc.py, asab/library/providers/filesystem.py, asab/library/providers/zookeeper.py, asab/library/service.py
@ateska New output from list
```
{
"path": "/",
"data": [
{
"name": "/1111111111}).md",
"type": "item_0"
},
{
"name": "/220906{})(.txt",
"type": "item_1"
},
{
"name": "/2222222222.md",
"type": "item_0"
},
{
"name": "/333333333.md",
"type": "item_0"
},
{
"name": "/777.md",
"type": "item_0"
},
{
"name": "/999.md",
"type": "item_0"
},
{
"name": "/Dashboards/",
"type": "dir"
},
{
"name": "/Filesystem.html",
"type": "item_1"
},
{
"name": "/Password reset.html",
"type": "item_1"
},
{
"name": "/Schemas/",
"type": "dir"
},
{
"name": "/Templates/",
"type": "dir"
},
{
"name": "/alert.md",
"type": "item_0"
},
{
"name": "/asabiris.json",
"type": "item_0"
},
{
"name": "/asimpletest.json",
"type": "item_0"
},
{
"name": "/asimpletestingfile.json",
"type": "item_0"
},
{
"name": "/avatar.md",
"type": …
```
=> Enhancement : Add library level info to list

test/__init__.py, test/test_crash/app_crash_01.py, test/test_crash/app_crash_02.py, test/test_crash/app_crash_03.py, test/test_crash/test_crash.py
An incident occurred when the asab application crashed without traceback when Exception was raised. These unit tests should help to prevent such incidents in the future.
=> Unit tests for crash control

asab/library/service.py
https://ndocs.teskalabs.com/asab/reference/library/reference/
- typing added
- docstrings converted to Google Style Guide
- renamed `_on_tick()` as it is a private method
=> Documentation for LibraryService

asab/pubsub.py, docs/reference/pubsub/reference.md, mkdocs.yml
=> WIP: Documentation for `PubSub`

.gitlab-ci.yml, mkdocs.yml
Change styling to blue, add CI pipeline to 'master' branch.
=> Documentation: integration

asab/log.py
=> Fix of the syslog handling when the socket is not yet ready.

asab/web/auth/service.py
=> Fix dev userinfo validation

asab/application.py, asab/web/auth/service.py
=> Add '--no-auth' argument

asab/library/providers/git.py
Reason why the periodic pull failed is displayed.
=> Git provider: Make periodic pull error descriptive

asab/sentry/service.py
```
release: LMIOCollectorApp:v23.40-alpha
```
=> Format release as 'appname:version'

asab/metrics/influxdb.py
closes #427 
Reformatting + handling generic exception when sending request to InfluxDB.
=> Add generic exception when sending request to InfluxDB

asab/library/providers/libsreg.py, examples/library.py
Proper fix for the https://github.com/TeskaLabs/asab/commit/511fdff3857b0f02df0f7527a56b2c23c02155e5
=> Fix of the libsreg provider in the asab.library.

asab/task.py
Small improvement that can help in implementations that needs to manage asyncio tasks.
=> Task service emits PubSub message when a task is finished.

asab/api/discovery.py
For all the microservices - the discovery hostname can be default, overriden by custom configuration.
=> Fix Discovery: Do not raise error when domain is not asab, proceed with the call

asab/api/discovery.py, asab/library/providers/git.py, asab/metrics/influxdb.py
Add a defensibility + fixing one nasty bug in InfluxDB/metrics.
=> Small but important fixes

asab/api/service.py
one-level dict where key must be a string and value msut be a set
```
{"baseline_id": ("baseline_124568")}
```
=> Draft: add more data to discover services

docs/reference/services/storage.md
This follows the changes in configuration options for Storage.
Related to: https://github.com/TeskaLabs/asab/pull/521 (elasticsearch)
Related to: https://github.com/TeskaLabs/asab/pull/553 (mongo)
=> Updates documentation: new config option for Storage

asab/web/auth/service.py
- Implements `request.has_tenant_access(tenant)` utility method.
- The method also performs superuser access check. :warning: Superuser always passes the has_tenant_access check - there is no check if the tenant actually exists.
- The method is available in all handlers where `asab.web.auth.AuthService` is installed.
```python
class MyApplication(asab.Application):
def __init__(self):
super().__init__()
self.add_module(asab.web.Module)
self.WebService = self.get_service("asab.WebService")
self.WebContainer = asab.web.WebContainer(self.WebService, "web")
self.WebContainer.WebApp.middlewares.append(asab.web.rest.JsonExceptionMiddleware)
self.AuthService = asab.web.auth.AuthService(self)
self.AuthService.install(self.WebContainer)
self.WebContainer.WebApp.router.add_get("/endpoint", …
```
=> Implement has_tenant_access utility method

asab-manifest.py, asab/api/log.py, asab/api/service.py
=> Convert utcnow() to now(datetime.timezone.utc)

asab/log.py
continues on this branch: https://github.com/TeskaLabs/asab/pull/576
The biggest disadvantage is the `copy()` mechanism used. It does not work without it.
If merged, we could start sing colors in docker again :)
=> Logging - fix formatting

asab/storage/mongodb.py
To remove from an existing array all instances of a value or values that match a specified condition.
https://www.mongodb.com/docs/manual/reference/operator/update/pull/
=> Pull an item from a list: mongo storage

asab/api/discovery.py
do not pass None as authorization header
fixes issue introduced by #621
=> Fix discovery service authorization

asab/web/auth/service.py
Auth cleanup did not work because of a missing pubsub argument.
=> Fix AuthService housekeeping

asab/web/auth/authorization.py
- Remove optional AuthorizedParty attribute.
- Add SessionId attribute.
- Add `get_claim()` method for accessing claims by key.
=> Revise Authorization attributes

asab/library/service.py
Update of docstrings in Library Service for methods where tenant must be specified explicitly as context variable.
=> LibraryService Documentation:  Tenant in contextvar

asab/web/auth/service.py, asab/web/tenant/providers/abc.py, asab/web/tenant/providers/static.py, asab/web/tenant/providers/web.py, asab/web/tenant/service.py, asab/web/tenant/utils.py
=> Tenant service now checks in the tenant exists.

asab/web/auth/service.py
HEAD requests must be authorized.
=> Remove auth exception for HEAD requests

asab/web/auth/authorization.py, asab/web/auth/decorator.py, asab/web/tenant/service.py, docs/reference/services/web/authorization.md, docs/reference/services/web/multitenancy.md
=> Satanic documentation fixes in auth and tenant hell

asab/web/auth/__init__.py
Remove `jwcrypto` dependency introduced by #665
=> Remove mandatory dependency on jwcrypto

asab/library/item.py, asab/library/providers/zookeeper.py, asab/library/service.py
List item is now updated to look like
```
{
"name": "/Parsers/item.1",
"type": "file",
"layers": [
"0:tenant",
"0:global",
2
],
},
```
=> New changes to list

asab/application.py, asab/library/providers/zookeeper.py, asab/zookeeper/service.py, asab/zookeeper/wrapper.py, examples/library.py
=> Better finalization sequence.

asab/web/container.py
=> Allow port as integer in web container config

asab/config.py, asab/metrics/service.py
... used in i.e. `lmio-franz` to deliver metrics **less* frequently.
=> Add a metric tick interval multiplier.
