- asab/web/websocket.py
- examples/webserver.py
I want to be able to send a response to the websocket from which I received a message like this:
```
class WSFactory(asab.web.WebSocketFactory):
async def on_message(self, request, message, websocket):
await websocket.send_json({"data":"pong"})
```
> Add the websocket object to WebSocketFactory's on_message.

- asab/web/rest/json.py
When using `asab.web.rest.json_response` with data from MongoDB it throws error `Object of type 'ObjectId' is not JSON serializable` (`ObjectId` is MongoDB identificator - `<class 'bson.objectid.ObjectId'>`)
This is to allow implementation of custom dumps object.
Example of usage `json_response(..., dumps=bson.json_util.dumps)`
> Allow custom dumps on json_response

- asab/pubsub.py
- examples/pubsub.py
b/c the set requires hashable object on the input which is not always possible.
> Switch PubSub from sets to lists for subscribers

- asab/__init__.py
- asab/__version__.py
- setup.py
`python -c 'import asab;print(asab.__version__)'` will print out `devel`
After creating a git tag (`git tag -a v19.10 -m "Release of asab v19.10" && git checkout v19.10`) following command will create a distribution package and replace `__version__` and `__build__` in `__version__.py`
`python setup.py sdist bdist_wheel`
Preview of `build/lib/asab/__version__.py` file
```py
__version__ = '19.10'
__build__ = 'da693b1b8de6ae448f5ff94dd79ebc538493c069'
```
> PLUM-764: Align versioning with bspump - from a git tag

- asab/web/rest/json.py
This is fixing typo in json error response
Original:
```
{
"mesage": "Bad Request",
"status": 400,
"uuid": "1c632c9a-b807-43df-9178-8cbb192f0c60"
}
```
Fixed:
```
{
"message": "Bad Request",
"status": 400,
"uuid": "1c632c9a-b807-43df-9178-8cbb192f0c60"
}
```
> Fix 'mesage' typo in json response

- asab/config.py
- asab/log.py
As a user I want to be able to configure logging level of the RootLogger.
In configuration:
```
[logging]
level=INFO
```
> Making RootLogger's logging level configurable.

- asab/web/authn/__init__.py
- asab/web/authn/middleware.py
@ateska I don't think `authorized_prefixes` is correct name. Shouldn't we use something more generic here?
Thanks.
> PLUM-1178: Initialize authorize_any and authorize_all handler

- asab/storage/__init__.py
- examples/inmemory_storage.py
- examples/mongodb_storage.py
ASAB storage was very sensitive on the order of configuration vs. module import and initialization.
This is now fixed and it should work nicely.
> Smarter ASAB storage selector

- asab/alert.py
This adds an Alert Service to ASAB.
It means that you can raise the alarm in e.g. OpsGenie or PagerDuty from the ASAB microservices.
The demonstration is implemented in SeaCat PKI
> Add an Alert Service

- asab/config.py
- examples/zookeeper.conf
- examples/zookeeper.py
Further development:
**Reuse of the ZooKeeper config**
```
[asab.zookeeper]
url=server1 server2 server3
[general]
include=zookeeper:///asab/etc/zk-site.conf
```
The server part of the URL is empty - it means that the URL from `asab.zookeeper` section should be used.
With the path in:
```
[asab.zookeeper]
url=server1 server2 server3
path=/myfolder
[general]
include=zookeeper:./etc/zk-site.conf
```
=> zookeeper://server1,server2, server3/myfolder/etc/zk-site.conf
> ASAB Config loading from ZooKeeper

- asab/api/service.py
- asab/application.py
- asab/config.py
- asab/web/container.py
- asab/web/service.py
**`BREAKING`** The web configuration section has been renamed from `asab:web` to `web`.
`asab:web` was added to obsolete aliases for backwards compatibility.
> Draft: Web section config refactoring

- asab/web/rest/json.py
If a datetime object has no timezone info, it is interpreted as UTC and the "Z" suffix is appended to it.
All non-UTC datetimes need to be made timezone-aware to be dumped correctly.
Example:
```python
response = {
"naive_utcnow": datetime.datetime.utcnow(),
"aware_utcnow":pytz.timezone('UTC').localize(datetime.datetime.utcnow()),
"naive_now": datetime.datetime.now(),  # this is wrong and should not be used
"prague_now": datetime.datetime.now().astimezone(pytz.timezone("Europe/Prague"))
}
```
will be dumped as
```json
{
"naive_utcnow": "2021-09-09T07:43:58.225941Z",
"aware_utcnow": "2021-09-09T07:43:58.225946+00:00",
"naive_now": "2021-09-09T09:43:58.225988Z", 
"prague_now": "2021-09-09T09:43:58.225991+02:00"
}
```
> JSONDumper: interpret naive datetime as UTC

- asab/zookeeper/container.py
For example:
This will be used in the asab-config zookeeper provider and microservice monitor.
> Zookeeper container initialize returns zookeeper client.

- asab/web/rest/json.py
Issue: The app responds with 500 Server Error when it receives a request with malformed JSON body.
Fix: Catch the error and respond with 400 JSON Decode Error.
> Return 400 if JSON request cannot be decoded

- asab/storage/mongodb.py
Issue: Sometimes there are multiple async requests to update the same DB object. Only the first one succeeds, the others crash with unintentional TypeError.
This raises KeyError instead.
> Mongo upsertor: Raise KeyError if DB object changes

- asab/web/rest/json.py
Remove `status` code from JSON body, add `result` message instead.
Example response:
```json
HTTP 404
{
"result": "NOT-FOUND",
"uuid": "1234-5678-9abcd",
"message": "Field 'name' not found"
}
```
> Json exception middleware: Add "result" to responses

- .gitignore
- asab/api/web_handler.py
- asab/metrics/prometheus.py
- test/__init__.py
- test/test_prometheus.py
I'd like to ensure my understanding of asab metrics and their representation in Prometheus is right. One metric in asab can store several values. 
After some considerations every asab-counter value is translated into separate metric in Prometheus. However, this strategy might not fit the needs. 
asab counter:
```
{
'Name': 'mycounter',
'Tags': {
'host': 'DESKTOP-6J7LEI1',
'unit': 'bytes',
'help': 'Example counter.',
'label': 'sth',
'other_label': 'sth_else'
},
'Values': {
'v1': 10,
'v2': 5
}
}
```
OpenMetrics output:
```
mycounter_v1_bytes_total{label="sth",other_label="sth_else"} 10
mycounter_v2_bytes_total{label="sth",other_label="sth_else"} 5
```
> OpenMetrics & Prometheus support

- .gitignore
- asab/api/web_handler.py
- asab/metrics/metrics.py
- asab/metrics/prometheus.py
- asab/metrics/service.py
- examples/metrics.py
- test/test_prometheus.py
Metrics in asab reset every 60 seconds. When Prometheus requests metrics, the Counters values of the last state before the last reset are sent together with the time of reset, which Prometheus accepts as metric point suffixed "_created". A Counter value changes every 60 seconds and during this period it is constant. On the other hand, current values of Gauges are provided whenever Prometheus requests.
> Fix counters presentation to Prometheus

- asab/config.py
- asab/utils.py
- `asab.ConfigParser._convert_to_seconds` has been moved to `asab.utils.convert_to_seconds` so it can be used anywhere in ASAB.
- `asab.Configurable` now has `getseconds`, `getint` and `getfloat` methods, analogically to `ConfigParser`
> Move convert_to_seconds from asab.ConfigParser to asab.utils

- asab/api/service.py
- asab/storage/elasticsearch.py
- setup.py
The `web` item is always empty in zookeeper when microservices advertise about themselves. That's because API Service, which makes this advertisement, is synchronous and advertises in application init time. However, this `web` information originates in WebContainer during async initialize() which happens **after** the advertisement. 
I just made the ApiService wait for WebContainer to initialize... Not very elegant, but working...
> Trying to advertise "web" into zookeeper

- examples/zookeeper.py
It is not really intuitive but crucial if there is more than one ZK container. When ApiService is implemented, there is always a need to handle two ZK containers.
> Example: Check for multiple ZK containers

- asab/storage/mongodb.py
This ensures that datetime objects retrieved from MongoDB contain UTC timezone info.
Closes #231
> Timezone-aware MongoDB

- asab/application.py
Issue: Specifying the `-w` flag causes the app to crash on startup.
Fix: If `-w` is specified, create `web` section in config defaults if it doesn't exist.
> Fix -w flag behavior

- asab/library/providers/zookeeper.py
Changes dependent on https://github.com/TeskaLabs/asab/pull/239#pullrequestreview-1027516577.
There is one more issue to be solved and that's DisabledPaths: https://github.com/TeskaLabs/asab/pull/239/files#r913014555
I removed allowed files extensions as I need to read more than just yaml files. (And the list was empty and non-existing anyway.)
> asab.library ZK provider fix after refactoring

- asab/storage/elasticsearch.py
- asab/storage/inmemory.py
- asab/storage/mongodb.py
- asab/storage/service.py
- asab/storage/upsertor.py
Create a webhook that is triggered by any `asab.storage.Upsertor.execute()` call and makes a **PUT request** to a pre-configured URL.
The webhook payload is a JSON containing the upsertor data (excluding sensitive `__`-prefixed fields).
To set the webhook up, provide a non-empty `webhook_uri` in the config:
```ini
[asab:storage:changestream]
webhook_uri=http://localhost:8080/webhook
```
> Storage webhook

- asab/docker/__init__.py
I found an obsolete docker section name in the default config. I find using docker sock as the default config convenient. I have never bumped into any situation when this config would be different.
> docker default config update

- asab/__init__.py
- doc/asab/log.rst
`asab.LogObsolete.warning("Use of the obsolete function", struct_data={'eol':'2022-31-12'})`
Log example:
```
21-Jul-2022 14:32:40.983884 WARNING OBSOLETE Using obsolete config section [asab:web]. Preferred section name is [web].
```
Closed issue #240
> Add an OBSOLETE logger.

- asab/library/providers/zookeeper.py
Based on the discussion here: https://github.com/TeskaLabs/asab/issues/254#issuecomment-1191752565
Providing .version.yaml should not be obligatory. There should be a silent error when .version.yaml is missing. 
Honestly, I am confused by the code there. Calling the loop from a thread in sync method is :exploding_head: Why cannot we just read the file?
@mithunbharadwaj - these changes will probably affect asab-library also...
@mithunbharadwaj - I can see pull request also about .disabled file - remember, please, there are also use cases for asab.library where .disabeld file does not exist. 
Aren't these things (versions, disabled) too specific for ASAB as a framework...?
> library - ZK - No more complaints about missing version file.

- asab/docker/__init__.py
- asab/docker/service.py
- With Ubuntu 22.04, **cgroup v2** is being used instead of cgroup v1. 
- cgroup v2 does not use `/proc/self/cgroup` file to store info about the group
- instead it is possible to find "docker/container/<container_id>" piece of information in `/proc/self/mountinfo`
- Unfortunately, this information somehow propagated from my governator docker container outside the container into the same file on my computer. (Don't know what that means.) 
- Thus, distinguishing whether the process is running in docker or not is dependent on `/.dockerenv` file. However, as some clever guy on [StackOverflow](https://superuser.com/questions/1021834/what-are-dockerenv-and-dockerinit) noted, this file is empty, and God knows why it is still there and when it disappears.
- **Needs to be tested across multiple …
> in_docker selfawareness with cgroup v2

- asab/api/doc.py
- asab/api/service.py
- asab/web/rest/json.py
- doc/asab/web/restapidocs.rst
- doc/index.rst
I did some voodoo, so there's a `json_schema` passed to swagger from the `json_schema_handler` decorator. Especially helpful in POST requests. 
I had troubles to write valid yaml into docstring when using tabs as indentation - because yaml did not read tabs and flake8 doesn't allow me to use spaces in the docstring instead.
swagger example: https://editor.swagger.io/
@ateska 
I guess that `Servers` and `Authorize` features should be added?
And anything more is up to @antoninvondrovic freestyle?
And some refactoring extracting some more functions instead of all the if/else might be needed. :)
> Improving Swagger docs

- asab/docker/service.py
:see_no_evil: 
It worked on all of my machines even with the mistake :see_no_evil:
> fix get_docker_container_id

- asab/library/providers/git.py
- Merge was a stupid idea.
- I'm not sure whether passing the reference and removing changes from work_dir by reset hard is a good choice, but much better. And Přemek-proof. 
- Pulling before the listing is stupid because the library service does recursive listing.
- Where is the "spot" in the library service to integrate the update indication? 
- Fetching once in a minute is... There will always be one-minute lag when updating the repository. And there is no way how to invoke the changes - how to make the provider fetch now and not in a minute.
- `pull` is not really "pull" now.
> WIP: Fix GitProvider

- asab/metrics/metrics.py
- asab/metrics/service.py
```
07-Sep-2022 09:37:37.365540 WARNING asab.metrics.influxdb Error when sending metrics to Influx: 400
{"error":"partial write: field type conflict: input field \"[eps.in](http://eps.in/)\" on measurement \"bspump.pipeline.eps\" is type integer, already exists as type float dropped=8"}
```
This is weird to me. 
Values in EPSCounter can never be `int` as there is line 129 dividing value by delta time and 0/`float` = 0.0, even 1/1 = 1.0. So where is the `int` coming from? The only possible way I can see right now is the `return` on line 123. But how... do they have some time machine there? I can't see it as possible.
> EPSCounter fix

- asab/web/websocket.py
I wanted to make some action when websocket connects, but overriding the `on_connect` method, I accidentally removed websocket "registration" - getting wsid. It was stupid and I could fix it in my implementation but maybe this could prevent someone else doing the same mistake.
> WebSocket Factory refactoring

- asab/storage/mongodb.py
- asab/storage/service.py
- asab/storage/upsertor.py
Closes #328 
- Option `webhook_uri` now accepts a list of whitespace-separated target URIs.
- `Upsertor.WebhookResponseData` is now a dict with webhook URIs as keys and the respective JSON responses as values.
> Storage: Accept multiple webhook URIs

- asab/metrics/web_handler.py
1) Corrected a typo in the Examples section (wrong endpoint name, reversed);
2) Complete metrics table (including web_requests metrics) is shown only if they have been explicitly asked for (the relevant parameter web_requests_metrics is True).
3) Corrected the logic behind tags parameter (returned tags for any string in the request, including False).
> Corrected logic of watch_metrics endpoint

- doc/asab/log.rst
An example of how you can set custom logger levels added to ASAB documentation.
> Update docs: logging with custom level configuration

- asab/library/providers/zookeeper.py
Important Note: If you are using asab.library, please be aware that breaking changes have been made. This means that your current code may not work as intended.
When specifying paths within asab.library, please follow these rules:
- All paths must start with a forward slash (/), even the root path.
- Folder paths must end with a forward slash (/).
- Item paths must end with an extension (e.g. .json).
To retrieve a list of items using the API, use the following syntax:
`GET /library/list/Dashboards/`
Alternatively, you can use the following code:
`await self.LibraryService.list("/Parsers/nginx-access-log/")`
> Defect: Zookeeper sometimes has forward slash at the end of path.

- asab/library/providers/zookeeper.py
- asab/zookeeper/container.py
- asab/zookeeper/service.py
- asab/zookeeper/wrapper.py
- doc/asab/zookeeper.rst
- doc/index.rst
- Refactorization of the way how Kazoo (Zookeeper client) is integrated with ASAB
- Clarification of the approach to the configuration
- Introduction of `ZOOKEEPER_SERVERS` environment variable
- Refactoring of the approach to advertisement, mainly to reduce number of versions created in Zookeeper
- Documentation
- Code that directly interacts with the Kazoo wrapper / client will need to be updated.
- `sequential` argument of `create()` method has been renamed to`sequence` (aligned with Kazoo)
- Watcher is removed (use Kazoo directly)
> Zookeeper integration refactored.

- asab/log.py
Trying to fix an [issue: Colors in logging should be disabled when running in the docker/podman](https://github.com/TeskaLabs/asab/issues/335).
> Feature: now colors are disabled when running in container

- asab/storage/elasticsearch.py
- asab/storage/inmemory.py
- asab/storage/mongodb.py
- asab/storage/upsertor.py
(https://github.com/TeskaLabs/asab/issues/370).
Now the user can call `.upsertor()` method with an optional argument `event_type`, which is `str` or `None` and it adds
```python
{"event_type": event_type}}
```
into webhook.
> Feature/Optional argument `event_type` added into `Upsertor.execute()` method

- asab/storage/elasticsearch.py
- asab/storage/inmemory.py
- asab/storage/upsertor.py
In `InMemoryUpsertor` , IDs were not automatically generated which caused getters and setters not working.
> Fix/generate id when not specified in `InMemory` storage

- asab/storage/service.py
fix (#380)
- AES Key is set to `None` if it is not specified in the config file
- `self.AESKey` -> `self._AESKey`
- new method `encryption_enabled()` which returns True if AES Key is not None or an empty string
> Fix: AESKey handling

- setup.py
The latest versions of pip require version tags to comply with PEP 440, which causes errors and prevents ASAB from installing.
PEP 440 requires that the **public** version field does not contain hyphens or pluses, hence it is not fully compatible with SemVer (https://peps.python.org/pep-0440/#semantic-versioning). 
The commit number, hash and the "dirty" string (generated by `git describe`) are moved to the **local** version field, separated from the public version by "+". For example, version formerly tagged `v22.06-rc6-291-g3021077+dirty` now becomes `v22.06-rc6+291-g3021077-dirty`.
> Make version tags compliant with PEP 440

- asab/library/providers/zookeeper.py
```
05-May-2023 06:31:58.716583 ERROR root Task exception was never retrieved
{'future': <Task finished coro=<ZooKeeperLibraryProvider._get_version_counter() done, defined at /usr/local/lib/python3.7/site-packages/asab/library/providers/zookeeper.py:188> exception=RuntimeError("There is no current event loop in thread 'AsabProactorThread_265'.")>}
File "/usr/local/lib/python3.7/site-packages/asab/library/providers/zookeeper.py", line 193, in _get_version_counter
await self.Zookeeper.ProactorService.execute(self._check_version_counter, version)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/asab/library/providers/zookeeper.py", line 216, …
```
> Fix issue with proactor using event loop.

- asab/web/auth/service.py
We could not proceed with implementing resources in bs-query. This helped, but I am a bit scared of touching this thing, so please, do check this twice. 
Also, I am a bit not happy about growing configuration needs. 
from my config:
```
[auth]
#dev_mode=yes
multitenancy=yes
public_keys_url=http://localhost:8181/openidconnect/public_keys
tenant_url=http://localhost:8181/tenant
```
is tenant_url really needed there?
> return True when resources are ok

- asab/web/auth/service.py
When the `dev_mode` is enabled, the `multitenancy` switch is ignored. 
The tenant parameter from query string is extracted if there is one, otherwise it is set to `None`.
> Optional multitenancy in dev mode

- asab/web/auth/service.py
- Instead of a periodic pull, try to reload auth server public keys anytime they are outdated or not ready at the time of request authentication.
- **`BREAKING`** Superuser can only access tenants that are authorized in the current session.
- Removed the `tenant_url` config option, which is no longer necessary.
> Reload auth public keys when needed

- asab/application.py
Add a method `app.restart()` that schedules a **hard restart** of the whole application.
This function works by using `os.execv()`, which replaces the current process with a new one (without creating a new process ID). Arguments and environment variables will be retained.
https://en.wikipedia.org/wiki/Exec_(system_call)
**IMPORTANT:** Please note that this will work on Unix-based systems only, as it uses a feature specific to Unix.
**A piece of advice:** Be careful while using this function, make sure you have some control over when and how this function is being called to avoid any unexpected process restarts. It is not common to use these types of function calls in Python applications.
> Add an application-level restart

- asab/pubsub.py
Missing exception handling for PubSub resulted in a very strange and non-deterministic propagation of an exception from the PubSub handler to a caller.
> Add an explicit exception handling to PubSub synchronous message delivery

- asab/web/auth/service.py
- examples/web-auth.py
When dev mode is enabled, a message of the following type is logged on startup:
```
01-Jun-2023 17:06:37.298255 WARNING asab.web.auth.service AuthService is running in DEV MODE. 
All web requests will be authorized with mock user info, which currently grants access to the following 
tenants: ['test-tenant', 'default']. To customize dev mode authorization (add or remove tenants and resources, 
change username etc.), provide your own user info in '/conf/dev-userinfo.json'.
```
Also added the tenant `default` to the default mock userinfo, since it is also used in asab webui dev mode.
> Verbose dev mode info when the app starts

- asab/library/providers/git.py
- PubSub messages cannot be sent from different thread (proactor)
- I removed other ways of authorization - I left only deploy key possibility as this is the only one functional and actively used.
> Fix: Subscribe to changes in library - gitprovider

- asab/library/providers/git.py
- doc/asab/library.rst
- examples/library-git-provider.py
- examples/library-subscribe.py
- An example of how to use git provider created.
- A small section about git provider added together with manual on Deploy Tokens on GitLab.
> Draft: Documentation: Git Provider in ASAB Library

- asab/library/providers/git.py
- asab/library/providers/zookeeper.py
- asab/library/service.py
- doc/asab/library.rst
- doc/asab/pubsub.rst
- doc/asab/web/auth.rst
- doc/index.rst
- I thought there is no asab-library configuration but it was not rendered
- I didn't find how to make the docs of GitProvider automatically, because of sys.exit() in there - sphinx is afraid to exit itself.. so this one must be manual
- there is sphinx 1.8.6 running on our readthedocs. Sphinx on reathedocs must be updated or tested aginst sphinx 1.8.6 locally. Many things work with 7.x (latest version), but not in the production.
- do not ignore red warnings when building the documentation - sphinx is trying to help you.
> Documentation: Library

- asab/api/doc.py
- asab/web/auth/service.py
- asab/web/rest/json.py
- examples/web-auth.py
Argument extraction was broken for decorated methods. This "unwraps" them before signature inspection.
> Fix auth for handlers with multiple decorators

- asab/application.py
- asab/config.py
Optionally trigger `Application.housekeeping!` at application startup. Disabled by default.
To enable, set `run_at_startup` to `yes`:
```ini
[housekeeping]
run_at_startup=yes
```
Or run the app with `--startup-housekeeping` command line argument.
> Optionally run housekeeping at startup

- asab/config.py
- json, yaml and conf files supported
- I had to swap defaults and includes (L197) - because ASAB_ZOOKEEPERS_SERVERS env variable is written into default conf. But I don't know whether I didn't break anything with that. 
- The separator between includes is newline or space - it means that space MUST NOT be in the names of nodes in Zookeeper. os.pathsep cannot be a separator for zookeeper paths. it breaks them.
> Load configuration from the zookeeper

- asab/application.py
```
#!/usr/bin/env python3
import logging
import asab
L = logging.getLogger(__name__)
class MyApplication(asab.Application):
async def main(self):
print("ahoj!")
raise Exception("this one is obvious")
if __name__ == "__main__":
app = MyApplication()
app.run()
```
> Fix: Allow exceptions in main function

- asab/tls.py
The CA certificate can be provided as a string PEM. eg loaded from Zookeeeper
> Extend the TLS opts on providing CA certificate.

- asab/storage/elasticsearch.py
- asab/tls.py
- examples/storage_elasticsearch.py
- Added new method `is_connected()` that checks the connection by sending GET requests to '/' endpoint.
- When no document with the specified ID is found, `KeyError` is raised.
- When authorization is needed and 401 code is returned, `ConnectionRefusedError` is raised.
- **Bugfix**: when `aiohttp.client_exceptions.ClientConnectorError` occured, the service should check all URLs and iterate through them till the last. If the last URL also gets the same Error, `ConnectionError` should be raised. Problem was that URLs were modified during the request processing so this case never happened and the only response was a warning message.
- **Bugfix**: some `StorageService` methods were referencing to `self.Storage` which is correct only for `Upsertor` methods.
- Methods `_insert_new_object()` and …
> Add API Key authorization option for ElasticSearch

- asab/library/providers/git.py
`pygit2` library produces very generic `GitError` with unreadable error message. This is an attempt to obtain something more descriptive.
- Authentication fails:
```
ERROR asab.library.providers.git [sd url=... username=... deploy_token=...] Authentication failed when initializing git repository.
Check if the 'providers' option satisfies the format: 'git+<username>:<deploy token>@<URL>#<branch name>'
```
- Incorrect URL:
```
ERROR asab.library.providers.git [sd url=...] Git repository not found.
```
- Branch does not exist:
```
ERROR asab.library.providers.git [sd url=... branch=...] Branch does not exist.
```
> Draft: GitLibraryProvider: better error messages

- asab/library/service.py
`LibraryService.subscribe()` method now allows a single path as a string.
> Add type control to `LibraryService.subscribe()`

- asab/application.py
- docs/reference/application/application.md
For the new makedocs documentation, I would like to:
- add docstrings for all the classes and public methods
- convert the existing docstrings to [Google style format](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings)
> Documentation: docstrings in `asab.Application`

- doc/asab/library.rst
I forgot how it works even though it is my code. So here is the documentation.
> Branch option in the gitprovider

- asab/__init__.py
- asab/alert.py
- asab/config.py
- asab/metrics/http.py
- asab/metrics/influxdb.py
- asab/tls.py
- asab/web/container.py
- asab/zookeeper/container.py
`asab.ConfigObject` -> `asab.Configurable`
`asab.ConfigObjectDict` -> `asab.ConfigurableDict`
fixes #464 
I will do the corrections in the new documentation later. I will inform TeskaLabs people about this since SeaCat Auth uses these objects.
> Rename ConfigObject to Configurable

- asab/config.py
- examples/config_getmultiline.py
Solves #460
It is just a small utility function for obtaining list from configuration where items are separated by space or newline.
```ini
[places]
visited:
Praha
Brno
Pardubice Plzeň
unvisited:
```
```python
>>> asab.Config.getmultiline("places", "visited")
["Praha", "Brno", "Pardubice", "Plzeň"]
>>> asab.Config.getmultiline("places", "unvisited")
[]
>>> asab.Config.getmultiline("places", "nonexisting", fallback=["Gottwaldov"])
["Gottwaldov"]
```
> Add `getmultiline` method

- asab/application.py
- docs/reference/application/reference.md
- docs/reference/modules_services/reference.md
- docs/reference/storage/reference.md
- Fixing referencing
- Some content moved to docstrings and vice versa
> Documentation: proofreading and small fixes

- asab/tls.py
- **BREAKING**: `password` config option in `asab.tls` renamed to `key_password`
closes #474 
Related issue: https://github.com/TeskaLabs/seacat-auth/pull/244#pullrequestreview-1571905790
> Rename TLS password config option to avoid name conflicts

- docs/getting-started/installation_first_app.md
- docs/how-tos/03_rest_api.md
- docs/how-tos/index.md
- docs/how-tos/installing-asab.md
- docs/reference/application.md
- docs/reference/configuration.md
- docs/reference/logging.md
- docs/reference/metrics/reference.md
- docs/reference/modules_services.md
- docs/reference/pubsub.md
- docs/reference/web/tls.md
- docs/reference/web/web-server.md
Some hyperlinks used absolute path (e.g. "/reference") which does not work on deployed documentation. This is now fixed.
> Fix invalid hyperlinks

- asab/metrics/influxdb.py
or - maybe "cleaner" solution:
```python
return {k.replace(" ", "\\ ").replace(",", "\\,").replace("=", "\\="): str(v).replace(" ", "\\ ").replace(",", "\\,").replace("=", "\\=") for k,  v in tags.items()}
```
In this case, the None tag would be "None". Which is still better than nothing and comprehensions are faster.
Original bug:
```
25-Aug-2023 09:01:34.107737 ERROR root Task exception was never retrieved
{'future': <Task finished coro=<InfluxDBTarget.process() done, defined at /usr/local/lib/python3.7/site-packages/asab/metrics/influxdb.py:104> exception=AttributeError("'NoneType' object has no attribute 'replace'")>}
File "/usr/local/lib/python3.7/site-packages/asab/metrics/influxdb.py", line 105, in process
rb = influxdb_format(m_tree, now)
File …
```
> Fix: Metrics must be sent even when tag is None

- asab/api/doc.py
Configure OpenAPI server URL (or multiple URLs) using the `[asab:doc] server_urls` option.
> Configurable OpenAPI server URL

- asab/library/service.py
Old implementation of the library stores the set instead of dictionary in `./disabled.yaml` - this causes problems.
> ASAB Library: Allow set in `.disabled.yaml`

- asab/application.py
- asab/web/auth/service.py
- docs/reference/web/authorization_multitenancy.md
- examples/web-auth.py
- The `enabled` and `dev_mode` options in the `[auth]` config section are combined into one. To enable mock mode (formerly known as dev mode), specify `enabled=mock`.
- `dev_user_info_path` renamed to `mock_user_info_path`.
- Default `public_keys_url` changed to `http://localhost:3081/.well-known/jwks.json`, which is in line with the latest Seacat Auth.
- "Dev mode" renamed to "mock mode".
- Fixed the `--no-auth` switch to act upon the app configuration.
> Merge `enabled` and `dev_mode` config switch

- asab/library/service.py
I don't know if anyone actually uses this option, but still...
```ini
[library]
providers=zookeeper://...
```
> Fix typo in Zookeeper

- asab/sentry/__init__.py
- asab/sentry/service.py
- docs/reference/sentry.md
This MR has evolved into documentation changes...
`SentryService` will be implemented into the code like this:
```python
if "sentry" in asab.Config.sections():
import asab.sentry
self.SentryService = asab.sentry.SentryService(self)
```
`data_source_name` is intended to be specified in the configuration, `$SENTRY_DSN` is the fallback.
Also, logging default levels were changed:
- ERRORS are sent as Events
- INFO+ are sent as breadcrumbs
> Sentry improvements

- asab/library/providers/azurestorage.py
- asab/library/providers/filesystem.py
- asab/library/providers/zookeeper.py
- asab/library/service.py
Since the new `getmultiline()` method exist, I would like to use it when listing providers.
List of providers can be now listed on separate lines as well as on one line separated by spaces or tabs.
```ini
[library]
providers:
./library
zk://zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/lmio-testing/library.lib 
git+http://lmio-box-testing:@gitlab.teskalabs.int/lmio/lmio-common-library.git
```
> Allow providers specification on separate lines

- asab/web/container.py
Handle the exception when user tries to bind on address that is already used.
Before:
```
12-Sep-2023 14:34:49.169395 ERROR asab.task Error '[Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use' during task:
File "/home/mir/Projects/Python/TeskaLabs/asab/asab/task.py", line 149, in main
await task
File "/home/mir/Projects/Python/TeskaLabs/asab/asab/web/container.py", line 149, in _start
await site.start()
File "/home/mir/.local/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
self._server = await loop.create_server(
File "/usr/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to …
```
> Handle error when address is already in use

- asab/web/auth/service.py
Introduced `is_enabled` method in `AuthService`.
```python
auth_service = app.get_service("asab.AuthService")
if auth_service.is_enabled():
...
```
> Method for checking if AuthService is enabled

- asab/storage/elasticsearch.py
```ini
[asab:storage]
elasticsearch_url=http://es01:9200,es02:9200,es03:9200
```
...the path will be "/".
```ini
[asab:storage]
elasticsearch_url=http://es01:9200,es02:9200,es03:9200/miluju/knedliky
```
...the path will be "/miluju/knedliky/"
> Allow paths without trailing slash in Elasticsearch config

- asab/library/providers/git.py
Provide better error message:
```
AttributeError: 'NoneType' object has no attribute 'remotes'
```
> Improve error messages in git provider

- asab/library/service.py
This MR introduces significant enhancements to the check_disabled method in LibraryService, including improved error handling, a correction in the logic for globally disable checks, and an update to the method's docstring for better clarity and documentation standards.
**Changes Made:**
1. Error Handling for Invalid Path Argument:
2. Logic Correction for Global Disable Check:
Modified the logic that checks if an item is disabled for all tenants. Previously, the method checked if disabled == '*', which was incorrect as disabled is expected to be a list.
The revised logic correctly checks for the presence of '*' in the disabled list, accurately identifying items that are globally disabled.
3. Updated the docstring to reflect the new error handling behavior and to provide a clearer …
> Enhanced Error Handling, Logic Correction, and Docstring Update in check_disabled Method

- asab/metrics/service.py
Closes #525 .
I am really not sure about this one. I would like to throw an exception if someone tries to create tags which are not key-value string pairs.
Someone give me a suggestion :)
> Metrics: convert tag keys and values to a string

- asab/pubsub.py
When exception is thrown in async PubSub message handler, then it is now collected and logged properly.
> Better exception handling in PubSub

- asab/storage/elasticsearch.py
This MR deals with corner cases.
The previous solution was not optimal: https://github.com/TeskaLabs/asab/pull/521
For example, when there was no data in `[asab:storage]` + no `[elasticsearch]` section 
```
[asab:storage]
type=elasticsearch
```
we got the error:
```
self.Headers = build_headers(username, password, api_key)
UnboundLocalError: local variable 'username' referenced before assignment
```
instead of a nice handling.
Also, there might be possible bugs introduced on lines 57 - 77 (for example, overwriting / ignoring variables) from different sections: https://github.com/TeskaLabs/asab/blob/5e8266210e9c0725273a376d79edcea120332f5e/asab/storage/elasticsearch.py#L57-L77 => for example, empty `[elasticsearch]` will overwrite `username/password/api_key` from `asab:storage` …
> New configuration section [elasticsearch]: better solution

- asab/metrics/influxdb.py
Reported errors:
```
02-Dec-2023 16:36:58.964712 ERROR asab.metrics.influxdb [sd url="http://lmio-box-testing-1:8086/"] Failed to send metrics to InfluxDB: [Errno -3] Try again
File "/usr/lib/python3.10/site-packages/asab/metrics/influxdb.py", line 138, in _worker_upload
conn.request("POST", self.WriteRequest, rb, self.Headers)
File "/usr/lib/python3.10/http/client.py", line 1283, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib/python3.10/http/client.py", line …
```
> Improved error handing of metrics propagation into InfluxDB.

- asab/web/metrics.py
- examples/metrics-web-requests.py
The first commit is a fix of the web requests histogram, where I missed one value in the buckets.
The second commit is there because Robin wanted the buckets to be configurable. I don't like it. But it cannot harm anything, either.
I think the default configuration should live here: https://github.com/TeskaLabs/asab/blob/master/asab/config.py#L48
But then, when you look into the code of web request metrics, it is not obvious what are the histogram buckets upper bound values.
> Fix web requests histogram

- asab/config.py
- asab/web/auth/service.py
It makes seacat auth resolvable through Discovery Session. 
I think it is not a breaking change. 
I moved default configuration to config.py, because I could not use asab.Config.add_defaults() inside by microservice - it was overriden by the add_default from AuthService. 
I tested this in bs-query. I could resolve seacat-auth within maestro installation, but I got 401 as I am calling to private web container. That is related to this: https://github.com/TeskaLabs/seacat-auth/pull/319
> Find seacat auth without configuration

- asab/api/doc.py
- asab/api/doc_templates.py
- asab/web/__init__.py
- examples/webserver.py
* change in `build_swagger_documentation` so that it propagates a host into the list of servers; it is more sane way of how to call "self" from Swagger, removing that relative URL
* improved way of how swagger is loaded to web server (thru index.html)
* added "shortcut" param "api" to `asab.web.create_web_server()` that enables swagger doc just by stating `api=True`
> Improve on the Swagger doc

- asab/library/providers/libsreg.py
Fixed - issue was manifested only if 2 and more libsreg layers were present in the configuration.
This is non-breaking change.
> LZMAError: Corrupt input data in libsreg library provider

- asab/api/service.py
- asab/metrics/service.py
- asab/sentry/service.py
- docs/reference/services/metrics/tags.md
- docs/reference/services/sentry.md
SITE ID environment variable will propagate:
- to data advertised into zookeeper through API Service
- to tags of metrics
- to sentry tags
> Add SITE_ID identifier

- asab/sentry/service.py
Since "environment" is mandatory tag in Sentry.io, we can set that tag to SITE_ID.
> Set "environment" tag in Sentry to SITE_ID

- asab/web/auth/service.py
- examples/web-auth.py
- **`BREAKING`**: Changed `asab.web.auth.AuthService`'s service_name to `asab.AuthService` (was incorrectly `asab.AuthzService`). I briefly checked our codebase and none of our services should be impacted by this potentially breaking change.
- Introducing `asab.web.auth.AuthService.get_authorized_tenant(request)`: A utility method for getting authorized tenant ID from the request's userinfo. If there is no authorized tenant or no authorization whatsoever, the return value is `None`.
- Updated auth examples and docstrings.
```python
async def endpoint(self, request):
auth_service = self.App.get_service("asab.AuthService")
tenant = auth_service.get_authorized_tenant(request)
if tenant is None:
return asab.web.rest.json_response(request, {"result": "ERROR"}, status=400)
else:
result = await …
```
> Fix AuthService name and introduce get_authorized_tenant utility method

- asab/api/doc.py
This fixes the generated specs to pass stricter validators (such as https://editor.swagger.io/)
> Fix OpenAPI specs to compile without errors

- asab/api/doc.py
- asab/api/doc_templates.py
- Route tag is now extracted from the YAML part of class dosctring. If not available, the tags are generated from class name or module name as before.
- ~~Updated CDN URL of scalar/api-reference since it has been updated on their github (https://github.com/scalar/scalar?tab=readme-ov-file#from-a-cdn) and the old one (on dpkg.com) stopped working.~~ The old URL still works, it just had a temporary outage.
> Get OpenAPI route tag form class docstring

- asab/application.py
The message
```
05-May-2024 03:08:21.418922 NOTICE asab.application [sd next_housekeeping_time="2024-05-06 03:00:00" next_time_limit="2024-05-06 05:00:00" next_housekeeping_id="20240506"] Setting time for the next housekeeping.
```
looks a little quirky and was there mainly for debugging. I want to rather see
```
05-May-2024 03:08:21.418922 NOTICE asab.application is performing housekeeping.
```
Also, when Housekeeping is missed for some reason, we can show ERROR that will be visible in Sentry.io etc.
```
05-May-2024 03:08:21.418922 ERROR One or more Housekeeping events have not been executed.
```
> Improve Housekeeping logging

- asab/config.py
- asab/log.py
I probably forgot some important piece...
But why don't we log into console by default? Always...? I don't recall any case when I would like NOT to see the logs.
> Log to console by default

- asab/storage/mongodb.py
Related to: https://github.com/TeskaLabs/asab/issues/573
The new MongoDB Storage configuration (https://github.com/TeskaLabs/asab/pull/553) will raise OBSOLETE warning for any provider that is not configured in the new section. 
```
[mongo]
uri=<.....>
database=<....>
```
However there are installations with multiple MongoDB providers that require separate sections in configuration file.
> Removes OBSOLETE warning: multiple MongoDB providers

- asab/exceptions.py
- asab/library/service.py
Right now, when you use incorrect path in `asab.LibraryService`, `AssertionError` is raised without an information about what path caused the trouble.
I suggest to create a custom Exception where you can access the "problematic" path and handle that in your microservice.
```python
try:
async with self.LibraryService.open(path) as f:
do_stuff()
except asab.exceptions.LibraryInvalidPathError as err:
L.error("Cannot read from path {}: invalid path!").format(err.Path)
```
Example of the exception message:
```
asab.exceptions.LibraryInvalidPathError: Invalid Library path '/lmio/library.lib': Directory path must end with '/' (e.g. '/Templates/Email/')
```
I also added `LogObsolete` warning when using `read()` method instead of `open()`...
Error is raised also when directory/item path contains …
> Custom exceptions for LibraryService

- asab/library/service.py
`open()` method internally used function `read()` and therefore obsolete warning was displayed every time. This separates these two methods completely.
> Separate read() and open() methods

- asab/api/discovery.py
I haven't fixed typing when the service was refactored. It should be matching when it is already there.
I don' want to add more, though.
> Discovery Service: fix typing

- asab/library/providers/abc.py
- asab/library/providers/azurestorage.py
- asab/library/providers/filesystem.py
- asab/library/providers/zookeeper.py
- asab/library/service.py
It seems like Sentry.io cannot handle properly some Exceptions driven by `asyncio.gather()` method, see this:
https://teskalabs.sentry.io/issues/5066136431/?query=start%3D2024-06-19T10%3A58%3A30%26end%3D2024-06-26T10%3A58%3A30%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream
- Some provider raises `KeyError` in `list()` method.
- This exception is handled in `LibraryService._list()` method so it is not propagated further in the application, you do not even receive error in logging,
- However, the error is apparently propagated to Sentry.io without full stack trace.
- `asyncio.as_completed()` method is used instead for concurrent listing from all providers
- `KeyError` error messages are more specific
- Some docstrings were modified
> Library - different approach for listing items from providers

- asab/storage/service.py
In `asab.storage` raw values are padded with `\x00` to fit the block size. When the raw value ends with `\x00`, it is mistakenly stripped away with `bytes.rstrip(b"\x00")` at decryption time, together with the padding.
- Use proper padding method from `cryptography.hazmat.primitives.padding`.
- Provide backward compatibility for existing encrypted entries.
> Use proper padding method when encrypting in asab.storage

- asab/library/providers/libsreg.py
- examples/library-git-provider.py
This MR addresses frequent "Failed to download the library (ClientError)." errors.
Also decreases the frequency of change checks for `v*` versions to once per 12 hours.
> ASAB library libsreg provider is more prone to failures

- asab/storage/mongodb.py
- asab/storage/service.py
#587 actually introduced a breaking change where items encrypted the old way cannot be decrypted anymore.
When proper decryption fails, try to decrypt the item the old flawed way and then update the database item with the new encryption.
> Repair items encrypted with broken padding method

- asab/api/discovery.py
- asab/web/auth/service.py
- examples/internal-auth.py
- There is one private key saved in zookeeper, shared by all cluster ASAB services.
- All services use it to generate JWTokens for the authorization of internal requests.
- AuthService adds the internal private key into its known keys.
To use the shiny new internal auth via discovery service, open a discovery session with argument `auth="internal"`:
```python
async with self.DiscoveryService.session(auth="internal") as session:
async with session.get("http://asab-myservice-1.instance_id.asab") as response:
...
```
To use the authorization from the incoming request (usually from the UI), open a discovery session with argument `auth=request`:
```python
async def some_handler(request):
async with self.DiscoveryService.session(auth=request) as session:
async with …
```
> Internal authorization via discovery service

- asab/application.py
- asab/config.py
> Kickoff: Add watchdog for loop interactivity.

- asab/library/providers/zookeeper.py
Hi, I have this is my microservice:
```
class ModelService(asab.Service):
def __init__(self, app, service_name='ModelService'):
super().__init__(app, service_name)
self.App.PubSub.subscribe("Library.ready!", self._on_library_ready)
self.App.PubSub.subscribe("Library.change!", self._on_library_change)
async def _on_library_ready(self, event_name, library=None):
await self.App.LibraryService.subscribe(["/Site/"])
async def _on_library_change(self, message, provider, path):
print(path)
```
the output of the print is 
`/Site/` for filesystem provider
and 
`/library/Site/` for ZK provider
The library methods should talk in library paths, so I want to change it to `/Site/` also for ZK provider. 
That means that the subscribed path cannot be changed.
> Library: Fix subscribe mechanism in ZK provider

- asab/api/discovery.py
Error was found:
`Non-thread-safe operation invoked on an event loop other than the current one`
The callback from kazoo has to stay on the "other" thread created in the proactor service. 
Přemek told me to use `asyncio.run_coroutine_threadsafe` to "return" the callback into the main thread.
However, I need to somehow take care of the resulting `Future` object as much as TaskService takes care of its tasks. 
It's a mess...
> Discovery Service: rescan threadsafe

- asab/task.py
is that right? I find it slightly too easy to be true. I don't know how to test in which thread the task is executed. However, it runs without errors
> Task Service: Schedule threadsafe

- asab/storage/elasticsearch.py
Add url encoding for the ES call, fixing an issue when (_id) contains "/" for example. In case of error, actually get it from the response object and log.
> Fix ES storage service delete method

- asab/library/providers/abc.py
- asab/library/providers/filesystem.py
- asab/library/providers/git.py
- asab/library/providers/libsreg.py
- asab/library/providers/zookeeper.py
- asab/library/service.py
- asab/web/auth/service.py
- examples/zookeeper-subscribe.py
- `LibraryService.subscribe` is extended with optional `target` argument.
- Possible `target` values:
- `None` (default) or `"global"` to watch global target changes,
- `"tenant"` to watch changes in ANY tenant,
- `("tenant", TENANT_ID)` to watch changes in a specific tenant.
- The callback method must expect `target` argument, whose value is either `"global"` or `("tenant", TENANT_ID)`.
- Backward compatibility: When  `LibraryService.subscribe` is called without `target` argument (or its value is `None`), the callback is called without `target` argument.
- Fix: Superuser has access to any tenant.
> Add target info to "Library.change!" pubsub message

- asab-manifest.py
- asab/api/service.py
I'm fighting with Franta for months! why remote control cannot send proper timestamps to the UI and I still could not understand...
So I had to find the respective UI part: http://gitlab.teskalabs.int/ateska/webui-microfrontends-poc/-/blob/master/asab_webui_components/src/components/DateTime/timeToString.js?ref_type=heads
Learning that UI simply uses library translating datetime in some ISO format. So I went through the specs: https://en.wikipedia.org/wiki/ISO_8601
And... sure it does not say "Just put Z in the end": https://github.com/TeskaLabs/asab/commit/8c16dea53f6434b8cf5f88533c0784c2e455c1b6
Who had the wonderful idea of "improving" iso format, so that is especially difficult to find what's wrong?
The timestamps from asab are the only ones, that cannot be translated by the UI to the …
> Api Service & Manifest: Fix timestamp, so it fits iso standard and can be further used

- asab/sentry/__init__.py
Transaction sampling can be disabled by setting `traces_sample_rate=0`, see:
https://docs.sentry.io/platforms/python/configuration/sampling/#configuring-the-transaction-sample-rate
> Sentry.io: Disable transaction sampling

- asab/library/providers/zookeeper.py
- examples/zookeeper-subscribe.py
follow-up to #603 
- The `target` argument is removed from `asab.library` pubsub callback. It is still kept in the `subscribe` method.
> Remove `target` argument from library's pubsub callback

- asab/library/providers/zookeeper.py
- asab/library/service.py
- asab/web/auth/__init__.py
- asab/web/auth/decorator.py
- asab/web/auth/service.py
- docs/reference/services/library.md
- examples/web-auth.py
Rules:
- In the module itself, we MUST use relative imports (no `import asab...` in ASAB but `from ...foo`)
- In 3rd party modules, we MUST use absolute imports, not `from` (no `from asab import ...`)
This MR also contains the extraction of the tenant from a Websocket Upgrade request.
> Fix of the incorrect imports

- asab/api/discovery.py
- examples/internal-auth.py
- When `asab.contextvars.Tenant` is set, `DiscoveryService.session()` automatically adds `X-Tenant` header to the request.
- There is also a new optional `tenant` argument in the `session()` method that can override the tenant context.
- Updated internal auth example.
No special action required, tenant is set automatically:
```python
discovery_svc = app.get_service("asab.DiscoveryService")
async with discovery_svc.session(auth="internal") as session:
async with session.get("http://my_application.service_id.asab/users") as resp:
data = await resp.json()
await do_stuff(data)
```
Before creating the session you need to set the value of `asab.contextvars.Tenant`, and reset the context after you are done with the session:
```python
import asab.contextvars
tenant_id = "cupcakes-corp" …
```
> Pass tenant to discovery session

- asab/web/tenant/service.py
- When `asab.web.tenant.TenantService` loads new tenants different from the previous state, a pubsub message `"Tenants.changed!"` is published.
- `asab.web.tenant.TenantService` now loads all tenants (including the ones from config) in the asynchronous initialization stage. This is to prevent multiple pubsub messages on app startup.
> Publish "Tenants.changed!" when new tenants are loaded

- asab/api/discovery.py
Passing authorization from incoming request to discovery service does not work because of wrong instance check.
The `auth` parameter must be instance of `aiohttp.web.Request`, not a client request.
> Fix request authorization in discovery service

- asab/library/service.py
- examples/library.py
`asyncio.as_completed()` does not keep the ordering of tasks and counts them as they are completed, therefore `layer` was wrongly counted here.
> Fix wrong layers counting in `library.list()` method

- setup.py
[Yarl 1.15.3 dropped support for Python 3.8](https://yarl.aio-libs.org/en/latest/changes/#removals-and-backward-incompatible-breaking-changes), as it has reached its end of life.
Add version-locked Yarl to ASAB dependencies.
> Lock Yarl version to keep python 3.8 compatibility

- asab/api/discovery.py
- asab/contextvars.py
- asab/web/container.py
- `asab.web.WebContainer` stores every incoming request in `asab.contextvars.Request`.
- `DiscoveryService.session` now uses the Authorization header from the Request context by default, so it is no longer necessary to specify `auth=request`.
```python
async def assign_ticket_to_user(self, request):
ticket_id = request.match_info["ticket_id"]
user_id = request.match_info["user_id"]
await self.TicketService.assign_ticket(ticket_id, user_id)
async def assign_ticket(self, ticket_id, user_id):
await self.Storage.put(ticket_id, user_id)
async with self.DiscoveryService.session(base_url="http://email-microservice.service_id.asab") as session:
async with session.put("/send", json={"message": "You have been assigned a ticket.", ...}) as resp:
...
```
> Implicit discovery session authorization using Request context variable

- asab/api/discovery.py
- examples/internal-auth.py
When `DiscoveryService.session(auth="internal")` is called and there is authorization in the context already, the following warning will be logged:
_25-Oct-2024 16:43:35.171971 WARNING asab.api.discovery Using internal (superuser) authorization in an already authorized context. This is potentially unwanted and dangerous._
> Warn on dangerous internal authorization usage

- asab/web/auth/service.py
In MOCK mode, you can specify Seacat Auth nginx introspection URL in the configuration so that incoming requests are immediately introspected without the need for reverse proxy. The introspection URL is not used in production mode (`enabled=yes`).
```ini
[auth]
enabled=mock
introspection_url=http://localhost:8900/nginx/introspect/openidconnect
```
> Direct auth introspection in mock mode

- asab/web/auth/service.py
`AuthService.get_authorized_tenant` has been removed but it is still used by baseliner.
Restore `AuthService.get_authorized_tenant` method and mark it as deprecated. It should be removed as soon as it is fixed and replaced in baseliner.
> Restore AuthService.get_authorized_tenant as a legacy method

- asab/api/discovery.py
- asab/web/auth/service.py
- :warning: BREAKING :warning: Providing tenant in HTTP request headers (`X-Tenant` or `Sec-WebSocket-Protocol`) is no longer possible. Tenant-aware endpoints must **expect `tenant` parameter in URL path or query.**
- :warning: BREAKING :warning: `DiscoveryService.session(...)` does not accept `tenant` argument anymore and does not pass Tenant context variable to the request. You must now **include tenant in the discovery URL explicitly.**
Example:
```python
async with DiscoveryService.session() as session:
async with session.get(
"http://ticket-app.instance_id.asab/{tenant}/tickets".format(tenant="bigcorporate")
) as resp:
...
async with session.get(
"http://ticket-app.service_id.asab/tickets?tenant={tenant}".format(tenant="bigcorporate")
) as resp:
...
```
> Deprecate X-Tenant header

- .github/workflows/ci.yaml
- setup.py
- Added support for Python 3.12 and 3.13
- CI/CD checkout is done with `fetch-depth: 0` to ensure git tags are available.
- Deprecated `python setup.py install` replaced with `pip install .`.
- custom_build_py should be a class.
> Add support for Python 3.12 and 3.13

- asab/web/tenant/service.py
@byewokko - please explain why that `if` is present.
It is causing problems when GET call is replaced by HEAD.
I propose to remove this if, unless there is a clear reason for that.
It causes monitoring (and likely more stuff) to broke.
> Removing exclusion for HEAD calls (tenant assignments)

- asab/library/providers/zookeeper.py
- asab/library/service.py
- asab/pubsub.py
- asab/zookeeper/container.py
- When library changes are not processed, path and tenant are in struct data now.
- Method `asab.library.LibraryService.find()` has corrected a misleading docstring - the function always returns a list.
> Small logging and docstring improvements in Library, ZooKeeper

- asab/config.py
- asab/web/auth/service.py
- asab/web/tenant/providers/static.py
- asab/web/tenant/providers/web.py
- asab/web/tenant/service.py
- asab/web/tenant/utils.py
- examples/web-auth.py
- Restore the functionality of `@allow_no_tenant` decorator.
- Fix auth and tenant web wrapper order checks.
- Tenant service requires at least one tenant provider to be configured (a list of tenant ids, URL with tenant ids, or both). If there is no provider at the async stage of initialization, tenant service logs an error:
```
04-Dec-2024 14:42:50.849680 ERROR asab.web.tenant.service TenantService requires at least one provider. 
Specify either `tenant_url` or `ids` in the [tenants] config section.
```
- Tenant service config defaults moved to `asab.config`.
> Fix the interaction of auth and tenant modules

- asab/api/doc.py
- asab/api/log.py
- asab/api/web_handler.py
- asab/metrics/web_handler.py
- `@allow_no_tenant` added to `/asab/v1/` handlers, since they are tenant-agnostic.
> ASAB API must require no tenant

- asab/web/auth/decorator.py
- asab/web/auth/service.py
- asab/web/tenant/decorator.py
- asab/web/tenant/service.py
- asab/web/tenant/utils.py
Improve traceback experience by replacing the generic name `wrapper` by more specific names.
> Rename closures named "wrapper" to be more specific

- asab/web/tenant/utils.py
Requests with `tenant` parameter both in URL path and query result in 400 Bad Request.
> Disallow using `tenant` parameter in path and query at the same time

- asab/api/doc.py
- asab/api/log.py
- asab/api/web_handler.py
- Path parameters taken from path are not added if they are described in route docstring.
- The first line of docstring is not duplicated in **name** and **description**.
- *asab* and *bspump* endpoints are at the bottom.
- Enhanced description for asab endpoints.
Example of path parameter taken from docstring:
Example of path parameter taken only from path :
Example of sorted tags in bspump application:
Examples of asab endpoints:
> Swagger: Fix duplicate path parameters

- asab/storage/mongodb.py
If the object was created using Mongo `asab.storage` upsertor without a version, the `_c` attribute was not filled.
This MR changes that and `_c` is set when the object is created without that.
> Mongo storage: If the object is new (version is 1), set the _c date to now

- asab/zookeeper/wrapper.py
ZooKeeper method `upsert()` now prioritizes `set()` before `create()`. To prevent race conditions, when `set()` fails but the node is created before `create()` is called, `set()` method is called again.
> ZooKeeper `upsert()` prioritizes `set()` before `create()`

- asab/web/tenant/providers/__init__.py
- asab/web/tenant/providers/zookeeper.py
- asab/web/tenant/service.py
Adds Zookeeper as the 3rd provider for `asab.TenantService`.
Returns Tenant IDs loaded from a dedicated ZK node.
Merge after this PR is ready and merged: https://github.com/TeskaLabs/asab/pull/652
This change will require:
- usual configuration in `[zookeeper]` section and
- an additional (new) configuration in `[tenants]` section:
```
[zookeeper]
servers=zookeeper-1:2181
[tenants]
zk_path=XXXXX
```
> Zookeeper Provider for Tenants

- asab/api/log.py
- asab/api/web_handler.py
- asab/metrics/web_handler.py
- asab/web/auth/__init__.py
- asab/web/auth/decorator.py
- Implemented `@asab.web.auth.require_superuser` decorator.
- Some ASAB API endpoints now require authorization, while the sensitive ones have been disabled completely.
- `/asab/v1/api/config` has been **disabled**.
- `/asab/v1/api/environ` has been **disabled**.
- `/asab/v1/api/manifest` is open.
- `/asab/v1/api/changelog` is open.
- `/asab/v1/api/log` requires `asab:service:access` authorization.
- `/asab/v1/api/logws` requires `asab:service:access` authorization.
- `/doc` is open.
- `/asab/v1/openapi` is open.
- `/oauth2-redirect.html` is open.
- `/asab/v1/api/metrics` is open*.
- `/asab/v1/api/watch_metrics` is open*.
- `/asab/v1/api/metrics.json` is open*.
*Metrics should be eventually protected (`asab:service:access`) but that would block Prometheus at the moment. I leave them open …
> Protect ASAB API

- asab/api/discovery.py
- Fixes incorrect condition for token renewal.
- Renewal frequency increased: New token is issued when it is less than 10 minutes before its expiration time.
> Fix internal auth token refresh period

- asab/contextvars.py
Introducing an utility for easier tenant context switching.
```python
import asab.contextvars
print(asab.contextvars.Tenant.get())  # LookupError
with asab.contextvars.tenant_context("mytenant"):
print(asab.contextvars.Tenant.get())  # "mytenant"
print(asab.contextvars.Tenant.get())  # LookupError
```
> Tenant context manager

- asab/metrics/service.py
- asab/metrics/storage.py
- test/test_metrics/baseclass.py
This MR adds an explicit delete method for metrics, so that other services can call it when they dispose of objects associated with the metrics (like Correlator object with PredicateMetrics).
> Add explicit delete metric method.

- asab/library/providers/zookeeper.py
Fixing "empty" exceptions when Library changes are not processed.
```
24-Apr-2025 09:49:46.419547 ERROR asab.library.providers.zookeeper [sd path="/EventLanes/"] Failed to process library changes: ''
24-Apr-2025 09:49:46.424906 ERROR asab.library.providers.zookeeper [sd path="/Site/"] Failed to process library changes: ''
24-Apr-2025 09:49:46.433586 ERROR asab.library.providers.zookeeper [sd path="/EventLanes/"] Failed to process library changes: ''
24-Apr-2025 09:49:46.439348 ERROR asab.library.providers.zookeeper [sd path="/EventLanes/"] Failed to process library changes: ''
24-Apr-2025 09:49:46.447071 ERROR asab.library.providers.zookeeper [sd path="/EventLanes/"] Failed to process library changes: ''
24-Apr-2025 09:49:46.454790 ERROR asab.library.providers.zookeeper [sd …
```
> Log exception when Library changes are not processed

- asab/web/auth/providers/id_token.py
Copy key providers before iteration to avoid "RuntimeError: Set changed size during iteration"
> Fix RuntimeError in KeyProviders iteration

- asab/library/providers/libsreg.py
I'll build e.g. remote control from branch and start it on fusion in debug mode to observe it for the whole 12 hours, to be sure. 
The same issue will be with detections library :exclamation:
> Hotfix versions library being checked too often

- asab/library/providers/zookeeper.py
- asab/library/service.py
issue:
```
09-Jun-2025 20:49:29.091407 WARNING kazoo.client Connection dropped: outstanding heartbeat ping not received
09-Jun-2025 20:49:29.092167 WARNING kazoo.client Transition to CONNECTING
09-Jun-2025 20:49:29.092580 WARNING asab.zookeeper.container [sd state="SUSPENDED"] ZooKeeper connection state changed. Zookeeper calls are now blocking!
09-Jun-2025 20:49:29.437043 NOTICE asab.zookeeper.container Connected to ZooKeeper.
09-Jun-2025 20:50:23.492384 ERROR asab.pubsub [sd task="asab.PubSub.Application.tick/600!"] Error during pubsub delivery
File "/usr/local/lib/python3.11/site-packages/asab/pubsub.py", line 281, in _deliver_async_exited
task.result()
File "/usr/local/lib/python3.11/site-packages/asab/library/providers/zookeeper.py", line 445, in …
```
> Fix for subscription size issue

- CHANGELOG.md
- asab/api/service.py
- asab/zookeeper/container.py
When asab.web server is initialised slowly (ie due to the system load), there is a race condition that can lead to incorrect advertisement to Zookeeper / Discovery service.
It is manifested by `"web": null` property in `/asab/run` service entry in ZK, which makes the service not discoverable.
- Advertisement is delayed until web container is ready.
- Handle quick changes in advertisements and delay the publishing of advertisements.
> Remove race condition from service advertisement in asab.api

- asab/zookeeper/wrapper.py
Added a method `get()` which directly copies [the original `kazoo.client.get()` method ](https://kazoo.readthedocs.io/en/latest/api/client.html#kazoo.client.KazooClient.get).
It is useful for getting metadata (like creation time) from a particular ZK node.
> Add get method into KazooWrapper

- CHANGELOG.md
- asab/web/auth/service.py
- asab/web/tenant/installer.py
- Do not apply tenant and auth handling to OPTIONS routes.
- Add path info to "Failed to initialize tenant context" error message:
```
RuntimeError: Failed to initialize tenant context for NotesApplication.list_notes ('/aaa/{tenant}/note'): 
In strict mode, all endpoint paths must start with '/{tenant}'.
```
> Do not apply tenant and auth handling to OPTIONS routes; improve init logging
